version: '3.5'

services:

  web:
    container_name: taiport_apache
    image: php:8.2.3-apache
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
    command: >
      bash -c "a2enmod rewrite && apache2-foreground"

  # mysql:
  #   container_name: taiport_mysql
  #   image: mysql:8.0.32
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "password"
  #   ports:
  #     - 3306:3306

  # phpmyadmin:
  #   container_name: taiport_phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 4040:80
  #   environment:
  #     PMA_HOST: 'mysql'
  #     PMA_USER: 'root'
  #     PMA_PASSWORD: 'password'
